### ISSUE TITLE
support unix-style stdin stdout

### ISSUE THREAD

**Issue by lukasheinrich** [eschanet/simplify#1]
Hi, 

it'd be great to have an API that does unix-style read from stdin / dump to stduot

```simplify --option foo < full.json > simplified.json```

```curl http://fo/likelihood.json | simplify --option foo | pyhf cls ```

**Comment by lukasheinrich** [comment]
(happy to pr this myself)

**Comment by eschanet** [comment]
I fully agree, this is actually on my todo list, but you know how this goes. If you have time to do it, feel free to open a PR, otherwise I'll just bump it up a bit in priority on my side! :-)
